services:
  django-backend:
    build:
      context: ./django-backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./django-backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db


  shop-frontend:
    build:
      context: ./shop-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./shop-frontend:/app
    command: >
      sh -c "npm install && npm start"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
